name: Test Python Code

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install and update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install uv and update dependencies
        run: | 
          pip install uv
          uv pip install -e . --system
      - name: Run pytest
        run: PYTHONPATH=$PWD pytest
